import java.sql.Timestamp;

/**
 * Created by android on 22/2/15.
 */
public class Match {
    String tournamentName;
    Timestamp dateAndTime;
    String value;
    String opponentTeam;
    int matchId;
    public static String matchQuery = " create table \"Matches\" (\"tournamentName\" VARCHAR(254) NOT NULL,\"dateAndTime\" TIMESTAMP NOT NULL,\"venue\" VARCHAR(254) NOT NULL,\"opponentTeam\" VARCHAR(254) NOT NULL,\"matchId\" INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY)\n";
}
