/**
 * Created by android on 22/2/15.
 */
public class Player {
    String name;
    int positionId;
    int playerId;
    public static String playerQuery = " create table \"Players\" (\"playerName\" VARCHAR(254) NOT NULL,\"positionId\" INTEGER NOT NULL,\"playerId\" INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY)alter table \"Players\" add constraint \"player_positionId_fk\" foreign key(\"positionId\") references \"Positions\"(\"positionId\") on update NO ACTION on delete NO ACTION\n";
}
