/**
 * Created by android on 22/2/15.
 */
public class Team {
    int matchId;
    int playerId;
    int teamId;
    public static String teamQuery = " create table \"Teams\" (\"matchId\" INTEGER NOT NULL,\"playerId\" INTEGER NOT NULL,\"teamId\" INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY)alter table \"Teams\" add constraint \"teams_matchId_fk\" foreign key(\"matchId\") references \"Matches\"(\"matchId\") on update NO ACTION on delete NO ACTIONalter table \"Teams\" add constraint \"teams_playerId_fk\" foreign key(\"playerId\") references \"Players\"(\"playerId\") on update NO ACTION on delete NO ACTION\n";
}
